services:
  flask-app:
    build: .
    command: ["python", "run.py"]
    ports:
      - "8001:8001"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app